name: Godot Builder

on: push
jobs:
# Set the job key. The key is displayed as the job name
# when a job name is not provided
  build-godot:
    # Name the Job
    name: Build Godot Engine
    # Set the type of machine to run on
    runs-on: "ubuntu-20.04"
    steps:
      # Clone Godot
      - name: Clone Engine
        uses: actions/checkout@v2
        with:
          path: 'engine'
          repository: 'funexpected/godot'
          ref: 'godot-3.2.3'
          ssh-key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          submodules: 'recursive'

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f engine/misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      # Install all packages (except scons)
      - name: Configure dependencies
        run: |
          sudo apt-get install build-essential pkg-config yasm libudev-dev

      - name: Check cc1obj
        run: |
          cc1obj -v
          execvp -v

      # Upload cache on completion and check it out now
      - name: Load .scons_cache directory
        id: linux-headless-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{github.ref}}
            ${{github.job}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version
      - name: Compilation
        env: 
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
        run: |
          cd engine
          scons -j8 platform=server tool=yes target=release_debug
